### ISSUE TITLE
Millheat API not working

### ISSUE THREAD

**Issue by Pimmp** [torandreroland/millheat-api#17]
After Mill updated their plattform this api no longer works.

**Comment by torandreroland** [comment]
Yes. I've made pull request #16 with support for the new Millnorwaycloud.

**Comment by Pimmp** [comment]
> Yes. I've made pull request #16 with support for the new Millnorwaycloud.

Much appreciated. Thx.

**Comment by torandreroland** [comment]
@Pimmp A version 2.0.0-beta.0 of homebridge-millheat has been published to npm. Can you test if it's working?
